TRUNCATE TABLE DATA;

INSERT INTO DATA (DATEREP,DAY,MONTH,YEAR,CASES,DEATHS,COUNTRIESANDTERRITORIES,GEOID,COUNTRYTERRITORYCODE,POPDATA2018,CONTINENTEXP) 
SELECT parsedatetime("DATEREP",'d/M/y'),DAY,MONTH,YEAR,CASES,DEATHS,COUNTRIESANDTERRITORIES,GEOID,COUNTRYTERRITORYCODE,POPDATA2018,CONTINENTEXP 
FROM CSVREAD('c:\Users\rofi\Downloads\world.csv');

select COUNTRIESANDTERRITORIES,SUM(cases) as CASES, SUM(DEATHS) as DEATHS, max(DATEREP) as DATEREP,POPDATA2018 from data group by COUNTRIESANDTERRITORIES;

select * from data where DATEREP= select MAX(DATEREP) from DATA;

CREATE TABLE "PUBLIC"."DATA"
(
   DATEREP date NOT NULL,
   DAY integer NOT NULL,
   MONTH integer NOT NULL,
   YEAR integer NOT NULL,
   CASES integer NOT NULL,
   DEATHS integer NOT NULL,
   COUNTRIESANDTERRITORIES varchar(42) NOT NULL,
   GEOID varchar(8) NOT NULL,
   COUNTRYTERRITORYCODE varchar(3),
   POPDATA2018 integer,
   CONTINENTEXP varchar(7) NOT NULL
);
