
name: Java CI with Maven

on: push
  
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Build with Maven
      run: mvn install
    - name: UploadWorldData
      run: wget -O tmp/world.csv https://opendata.ecdc.europa.eu/covid19/casedistribution/csv
    - name: Run Data Aggregator
      run: java -jar target/DataUpdater_exec.jar
    - name: Show run results
      run: ls -la dist/data
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftpupload.net
        FTP_USERNAME: epiz_25412810
        FTP_PASSWORD: ${{secrets.geokei_ftp_add_data}}
        LOCAL_DIR: dist
        REMOTE_DIR: geokei.com/htdocs
      
